import type { Vehicle } from "@/types/vehicle";

/**
 * Dev-only mock inventory mirroring supabase/seed.sql. Used by the data layer
 * when Supabase credentials are not configured, so the site renders and can be
 * demoed before keys are added. Never used once Supabase is configured.
 */
const now = "2026-06-01T12:00:00.000Z";

function photos(vehicleId: string): Vehicle["vehicle_photos"] {
  return [
    { id: `${vehicleId}-p0`, vehicle_id: vehicleId, url: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=1200&q=80", sort_order: 0, is_primary: true, created_at: now },
    { id: `${vehicleId}-p1`, vehicle_id: vehicleId, url: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=80", sort_order: 1, is_primary: false, created_at: now },
    { id: `${vehicleId}-p2`, vehicle_id: vehicleId, url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80", sort_order: 2, is_primary: false, created_at: now },
  ];
}

function features(vehicleId: string): Vehicle["vehicle_features"] {
  return [
    { id: `${vehicleId}-f0`, vehicle_id: vehicleId, feature_name: "Backup Camera", category: "Safety" },
    { id: `${vehicleId}-f1`, vehicle_id: vehicleId, feature_name: "Bluetooth", category: "Technology" },
    { id: `${vehicleId}-f2`, vehicle_id: vehicleId, feature_name: "Cruise Control", category: "Convenience" },
    { id: `${vehicleId}-f3`, vehicle_id: vehicleId, feature_name: "Power Windows", category: "Convenience" },
    { id: `${vehicleId}-f4`, vehicle_id: vehicleId, feature_name: "Keyless Entry", category: "Convenience" },
  ];
}

function badges(vehicleId: string, types: string[]): Vehicle["vehicle_prep_badges"] {
  return types.map((t, i) => ({
    id: `${vehicleId}-b${i}`,
    vehicle_id: vehicleId,
    badge_type: t as NonNullable<Vehicle["vehicle_prep_badges"]>[number]["badge_type"],
    created_at: now,
  }));
}

const base = {
  msrp: null,
  description_ai: null,
  meta_description: null,
  dc_vehicle_url: null,
  video_url: null,
  created_at: now,
  updated_at: now,
  sold_at: null,
  dc_last_synced: now,
  seats: 5,
  carfax_badge_great_value: false,
  carfax_badge_good_value: false,
};

export const MOCK_VEHICLES: Vehicle[] = [
  {
    ...base,
    id: "mock-1",
    vin: "1HGCV1F34LA042817",
    stock_number: "RT1001",
    year: 2020,
    make: "Honda",
    model: "Accord",
    trim: "LX",
    body_style: "Sedan",
    exterior_color: "Modern Steel Metallic",
    interior_color: "Black Cloth",
    mileage: 68420,
    price: 17995,
    status: "active",
    transmission: "CVT Automatic",
    drivetrain: "FWD",
    fuel_type: "Gasoline",
    engine: "1.5L Turbo I4",
    doors: 4,
    description_dc: "Well-maintained Honda Accord LX with strong service history. Clean interior, cold A/C, highway miles.",
    slug: "2020-honda-accord-lx-rt1001",
    carfax_url: "https://www.carfax.com/vehicle/1HGCV1F34LA042817",
    carfax_badge_one_owner: true,
    carfax_badge_accident_free: true,
    carfax_badge_service_records: true,
    featured: true,
    ryans_pick: true,
    ryans_take: "This is the kind of car I'd put my own family in. Boring in the best way — it just works.",
    best_fit_for: "Daily commuters who want low running costs and a comfortable highway ride.",
    what_to_know: "Tires have about 50% tread left. Factor a set into your budget over the next year.",
    days_in_inventory: 12,
    price_reduced: false,
    original_price: null,
    vehicle_photos: photos("mock-1"),
    vehicle_features: features("mock-1"),
    vehicle_prep_badges: badges("mock-1", ["state_inspection", "oil_change", "detailed", "multi_point_review"]),
  },
  {
    ...base,
    id: "mock-2",
    vin: "5TDZA23C16S512384",
    stock_number: "RT1002",
    year: 2019,
    make: "Toyota",
    model: "RAV4",
    trim: "LE",
    body_style: "SUV",
    exterior_color: "Magnetic Gray",
    interior_color: "Black Fabric",
    mileage: 74210,
    price: 19450,
    status: "active",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    fuel_type: "Gasoline",
    engine: "2.5L I4",
    doors: 4,
    description_dc: "AWD RAV4 LE with Toyota Safety Sense. One owner, no reported accidents, dealer-serviced.",
    slug: "2019-toyota-rav4-le-rt1002",
    carfax_url: "https://www.carfax.com/vehicle/5TDZA23C16S512384",
    carfax_badge_one_owner: true,
    carfax_badge_accident_free: true,
    carfax_badge_service_records: true,
    featured: true,
    ryans_pick: false,
    ryans_take: null,
    best_fit_for: "Families who need AWD confidence and Toyota reliability without a new-car payment.",
    what_to_know: "Small door ding on rear passenger side — priced accordingly. Come see it in person.",
    days_in_inventory: 8,
    price_reduced: false,
    original_price: null,
    vehicle_photos: photos("mock-2"),
    vehicle_features: features("mock-2"),
    vehicle_prep_badges: badges("mock-2", ["state_inspection", "oil_change", "detailed", "multi_point_review"]),
  },
  {
    ...base,
    id: "mock-3",
    vin: "1FTEW1EP5JFB28401",
    stock_number: "RT1003",
    year: 2018,
    make: "Ford",
    model: "F-150",
    trim: "XLT SuperCrew",
    body_style: "Truck",
    exterior_color: "Oxford White",
    interior_color: "Gray Cloth",
    mileage: 98750,
    price: 23900,
    status: "active",
    transmission: "10-Speed Automatic",
    drivetrain: "4WD",
    fuel_type: "Gasoline",
    engine: "2.7L EcoBoost V6",
    doors: 4,
    seats: 6,
    description_dc: "F-150 XLT SuperCrew 4x4 with tow package. Work-ready, runs strong, recent state inspection.",
    slug: "2018-ford-f-150-xlt-supercrew-rt1003",
    carfax_url: "https://www.carfax.com/vehicle/1FTEW1EP5JFB28401",
    carfax_badge_one_owner: false,
    carfax_badge_accident_free: true,
    carfax_badge_service_records: false,
    featured: true,
    ryans_pick: true,
    ryans_take: "Trucks at this price usually look rough. This one doesn't. Bed liner's already in it.",
    best_fit_for: "Anyone who needs a real work truck — towing, hauling, job sites.",
    what_to_know: "Higher mileage, but the EcoBoost has been serviced regularly. Carfax shows the records.",
    days_in_inventory: 21,
    price_reduced: true,
    original_price: 24900,
    vehicle_photos: photos("mock-3"),
    vehicle_features: features("mock-3"),
    vehicle_prep_badges: badges("mock-3", ["state_inspection", "detailed", "multi_point_review"]),
  },
  {
    ...base,
    id: "mock-4",
    vin: "2T1BURHE5KC198342",
    stock_number: "RT1004",
    year: 2019,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    body_style: "Sedan",
    exterior_color: "Classic Silver",
    interior_color: "Ash Fabric",
    mileage: 61300,
    price: 14495,
    status: "active",
    transmission: "CVT Automatic",
    drivetrain: "FWD",
    fuel_type: "Gasoline",
    engine: "1.8L I4",
    doors: 4,
    description_dc: "Economical Corolla LE — excellent first car or commuter. Great fuel economy, easy to insure.",
    slug: "2019-toyota-corolla-le-rt1004",
    carfax_url: "https://www.carfax.com/vehicle/2T1BURHE5KC198342",
    carfax_badge_one_owner: false,
    carfax_badge_accident_free: true,
    carfax_badge_service_records: true,
    featured: false,
    ryans_pick: false,
    ryans_take: null,
    best_fit_for: "First-time buyers and students who need cheap, dependable transportation.",
    what_to_know: "Previous owner was a smoker — we've detailed it twice and it's nearly gone, but be aware.",
    days_in_inventory: 35,
    price_reduced: false,
    original_price: null,
    vehicle_photos: photos("mock-4"),
    vehicle_features: features("mock-4"),
    vehicle_prep_badges: badges("mock-4", ["state_inspection", "oil_change", "detailed"]),
  },
  {
    ...base,
    id: "mock-5",
    vin: "5XYPGDA38LG612907",
    stock_number: "RT1005",
    year: 2020,
    make: "Kia",
    model: "Telluride",
    trim: "S",
    body_style: "SUV",
    exterior_color: "Ebony Black",
    interior_color: "Gray SynTex",
    mileage: 82150,
    price: 24800,
    status: "active",
    transmission: "8-Speed Automatic",
    drivetrain: "FWD",
    fuel_type: "Gasoline",
    engine: "3.8L V6",
    doors: 4,
    seats: 8,
    description_dc: "Three-row Telluride S with room for eight. Apple CarPlay, blind spot monitoring, rear cross traffic alert.",
    slug: "2020-kia-telluride-s-rt1005",
    carfax_url: null,
    carfax_badge_one_owner: false,
    carfax_badge_accident_free: false,
    carfax_badge_service_records: false,
    featured: false,
    ryans_pick: false,
    ryans_take: null,
    best_fit_for: "Bigger families who need three usable rows without stepping up to a full-size SUV price.",
    what_to_know: "Carfax report pending — ask us and we'll pull it for you before you visit.",
    days_in_inventory: 5,
    price_reduced: false,
    original_price: null,
    vehicle_photos: photos("mock-5"),
    vehicle_features: features("mock-5"),
    vehicle_prep_badges: badges("mock-5", ["detailed", "multi_point_review"]),
  },
  {
    ...base,
    id: "mock-6",
    vin: "1G1ZD5ST1JF134756",
    stock_number: "RT1006",
    year: 2018,
    make: "Chevrolet",
    model: "Malibu",
    trim: "LT",
    body_style: "Sedan",
    exterior_color: "Summit White",
    interior_color: "Jet Black Cloth",
    mileage: 89900,
    price: 9995,
    status: "active",
    transmission: "6-Speed Automatic",
    drivetrain: "FWD",
    fuel_type: "Gasoline",
    engine: "1.5L Turbo I4",
    doors: 4,
    description_dc: "Budget-friendly Malibu LT. Drives straight, cold A/C, new front brake pads at inspection.",
    slug: "2018-chevrolet-malibu-lt-rt1006",
    carfax_url: "https://www.carfax.com/vehicle/1G1ZD5ST1JF134756",
    carfax_badge_one_owner: false,
    carfax_badge_accident_free: false,
    carfax_badge_service_records: true,
    featured: false,
    ryans_pick: false,
    ryans_take: null,
    best_fit_for: "Budget shoppers who want a comfortable mid-size sedan under $10k.",
    what_to_know: "Has one prior reported accident (minor, front bumper) — fully disclosed on the Carfax. Priced to reflect it.",
    days_in_inventory: 18,
    price_reduced: true,
    original_price: 10995,
    vehicle_photos: photos("mock-6"),
    vehicle_features: features("mock-6"),
    vehicle_prep_badges: badges("mock-6", ["state_inspection", "detailed", "new_brakes"]),
  },
];
